### ISSUE TITLE
Expected behavior for NaN annotations

### ISSUE THREAD

**Issue by richard-warren** [jgraving/DeepPoseKit#23]
Thanks for the great package! What is the expected behavior of DataGenerator for annotations set to NaN in the annotations h5 file? I use my own labeling GUI and set to NaN all features that are not present within a frame. However, the DataGenerator spits out very large negative numbers (-999999) rather than nan for the annotations set to nan in the annotation h5 file. Is this correct, and will the keras generator spit out all-zero target maps for these features?

Thank you,
Rick

**Comment by jgraving** [comment]
Hi Rick, Yes, this is expected behavior (see https://github.com/jgraving/DeepPoseKit/blob/master/deepposekit/io/BaseGenerator.py#L125). This was a quick workaround to allow the `TrainingGenerator` to work with NaN annotations. Because keypoint coordinates are defined by the height and width of the image, setting NaN annotations to a large negative number ensures that the confidence maps will be set to all zeros, even if the images are augmented such that the coordinate space is shifted.

**Comment by richard-warren** [comment]
Perfect, thanks!

**Comment by richard-warren** [comment]
I recently observed that if a feature is set to NaN (such that it's position is set to [-999999, -999999]), but it is connected to a feature not set to NaN, the skeleton connecting these features actually 'reaches out' to [-999999, -999999]. My repo is a few commits behind; are you aware of this issue and has it been fixed?

Thanks!
Rick

**Comment by richard-warren** [comment]
I'm closing this because the bug in the graph drawing was address in issue #52
