### ISSUE TITLE
Poor performance with StackedDenseNet

### ISSUE THREAD

**Issue by richard-warren** [jgraving/DeepPoseKit#28]
I'm finding that DeepPoseKit underperforms DeepLabCut (both used within the DPK package) when there are long range spatial contingencies in the data. See the image below, where the left and right paw in the top view are swapped (this appears to happen less frequently with DLC). The bottom view is useful here for resolving ambiguities in the top view; I think deeper networks (DLC) may have an easier time with these long range contingencies due to greater receptive field size at the outputs. Perhaps there are tweaks I can make to DPK that solve the problem though.

![image](https://user-images.githubusercontent.com/31221441/68795939-ec834480-061f-11ea-83f2-2a1666ad80e8.png)

Here is my augmentation (notice no FlipAxis):
```
augmenter = []
sometimes = []

sometimes.append(iaa.Affine(scale={"x": (0.98, 1.02), "y": (0.98, 1.02)},
                            translate_percent={'x': (-0.02, 0.02), 'y': (-0.02, 0.02)},
                            shear=(-8, 8),
                            order=ia.ALL,
                            cval=ia.ALL,
                            mode=ia.ALL)
                 )
sometimes.append(iaa.Affine(scale=(0.9, 1.1),
                            mode=ia.ALL,
                            order=ia.ALL,
                            cval=ia.ALL)
                 )
augmenter.append(iaa.Sometimes(0.75, sometimes))
augmenter.append(iaa.Affine(rotate=(-5, 5),
                            mode=ia.ALL,
                            order=ia.ALL,
                            cval=ia.ALL)
                 )
augmenter = iaa.Sequential(augmenter)
```

And here is the model configuration:
```
{'name': 'StackedDenseNet',
 'n_stacks': 2,
 'n_transitions': 6,
 'growth_rate': 32,
 'bottleneck_factor': 1,
 'compression_factor': 0.5,
 'pretrained': True,
 'subpixel': True}
```
Thank you in advance for the help,
Rick

**Comment by jgraving** [comment]
It's hard to say because there are many hyperparameters at play, and we did not do any type of parameter sweep or architecture search in the paper.

The size of the receptive field is plenty large, as `n_transitions` indicates the number of times the images are downsampled within the network. In this case the minimum receptive field is 2**6 * (3, 3) = (192, 192), which is actually much larger due to stacked 3x3 convolutions and a 7x7 convolution in the first layer of the network. The receptive field may actually be too large, which can also be a problem as the network loses some of its translation invariance in the deepest part of the network.

I would first try adjusting `n_transitions` to be smaller. The default is -1, which downsamples the images as many times as possible (6 in this case). However, you may need to increase the `growth_rate` or `n_stacks` to increase the number of parameters. Another way to alleviate this problem may be to apply more aggressive augmentation for translating (and perhaps rotating) the image, as this forces the deepest features to preserve translation invariance.

If you're using a custom data generator, it may also be useful to set your posture graph to connect the corresponding body parts in the top and bottom of the image. This explicitly forces the network to learn the relationships between them. Adding these confidence maps should be relatively inexpensive for running inference.   

The `pretrained` option is also experimental and hasn't been thoroughly benchmarked yet, so there may be a bug how this part of the model is implemented. It might be worth trying `pretrained=False` if you haven't already.

**Comment by richard-warren** [comment]
Quick update: I took your suggestions and 1) turned off pre-training and 2) used more severe augmentation (in particular, increasing the resizing to range from .6->1.4). Performance is much improved. I was already connecting features in the top and bottom views with the skeleton per your suggestion. I may do a grid search, in which case I'll post the results here. Thanks!
